'use client';
import Link from "next/link"
import "./globals.css"
import { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] })

export const metadata:Metadata = {
  title: "Chat GPT Genereted Blog Post",
  description: "Generated by Next.js, Vercel, Chat GPT",
  keywords: "AI,yapay zeka,chat gpt,chatbot,chat bot,vercel",
}

interface RootLayoutProps {
  children: React.ReactNode
}
const customStyles = {
  content: {
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
  },
};
export default function RootLayout({ children }: RootLayoutProps) {
  
  const [isOpen, setIsOpen] = useState(false)
  function closeModal() {
    setIsOpen(false);
  }
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-2xl mx-auto py-10 px-4">
            <header>
              <div className="flex items-center justify-between">
                <nav className="ml-auto text-sm font-medium space-x-6">
                  <Link href="/">Blog</Link>
                  <Link href="/about">Hakkında</Link>
                  
                  <Link href="https://github.com/mirzaKarahan">GitHub</Link>
                </nav>
              </div>
            </header>
            <main>{children}</main>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}
