import { allPosts } from "@/.contentlayer/generated"
import Link from "next/link"
import { Metadata } from "next"


interface PageProps {
  params: {
    slug: string[]
  }
}
export async function generateMetadata({params,}: PageProps): Promise<Metadata> {
  return {
    title: "Chat GPT Genereted Blog Post",
    description: "Generated by Next.js, Vercel, Chat GPT",
    keywords: "AI,yapay zeka,chat gpt,chatbot,chat bot,vercel",
  }
}

export default function Home() {
  let sirali = JSON.parse(JSON.stringify(allPosts));
  sirali.map((p: any) => {
    console.log(p.date);
    p.date = Date.parse(p.date?.toString() || "2023-08-10");
  })
  sirali = sirali.sort((a: any,b: any) => b.date - a.date);
  return (
    <div className="prose dark:prose-invert">
      {sirali.map((post: any) => (
        <article key={post._id}>
          <Link href={post.slug}>
            <h2>{post.title}</h2>
          </Link>
          {post.description && <p>{post.description}</p>}
        </article>
      ))}
    </div>
  )
}
